services:
  mongodb:
    image: mongo:latest  # <--- Use 'latest' or '7.0' here
    container_name: mongodb
    ports:
      - "27007:27017" # 27017 -> is the default port , 2007 -> is one i will use
    volumes:
      - mongodata:/data/db # it will create the db in this location
    networks: # it should run on virtual network to access some ports and so on.
      - backend

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    restart: always # in case of fail -> restart

  pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
    restart: always
  
networks:
  backend:

volumes:
  mongodata:
  pgvector_data:

# docker compose up to run